siteTitle = 'Món Ngon Phú Quốc'
siteDescr = 'Đồ ăn & uống ngon'
siteDescription = "Những món ăn, đặc sản mọi miền Tổ Quốc"
siteUrl = "https://tonosdellamada.net"
siteBandcampUrl = 'https://tonosdellamada.net'
siteMenuOne = 'Đồ Ăn'
siteMenuTwo = 'Đồ Uống'
siteMenuThree = 'Quan tâm'
siteAddress = 'Địa chỉ: 165 Nguyễn Trung Trực, Thị trấn Dương Đông, Thành phố Phú Quốc'
siteAddress2 = 'Tỉnh Kiên Giang, Việt Nam. Postal code 920000'
sitePhone = '0899155555'
sitePhoneLink = 'tel:+84-089-915-5555'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
